"""add employee banking details

Revision ID: 0fa3b126bba8
Revises: 6a35fb3cdfb6
Create Date: 2026-07-25 20:17:30.817947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa3b126bba8'
down_revision = '6a35fb3cdfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_code')
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
