"""Create payroll records table

Revision ID: 2fcf6b56b26b
Revises: 0f6148664f54
Create Date: 2026-07-12 21:19:31.893386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcf6b56b26b'
down_revision = '0f6148664f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nssa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paye', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aids_levy', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('allowances_total >= 0', name='ck_payroll_record_allowances_non_negative'),
    sa.CheckConstraint('basic_salary >= 0', name='ck_payroll_record_basic_salary_non_negative'),
    sa.CheckConstraint('net_pay >= 0', name='ck_payroll_record_net_pay_non_negative'),
    sa.CheckConstraint('overtime_amount >= 0', name='ck_payroll_record_overtime_non_negative'),
    sa.CheckConstraint('total_deductions >= 0', name='ck_payroll_record_deductions_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_period_id', 'employee_id', name='uq_payroll_record_period_employee')
    )
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_records_payroll_period_id'), ['payroll_period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_records_payroll_period_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_records_employee_id'))

    op.drop_table('payroll_records')
    # ### end Alembic commands ###
