"""add Botswana irregular PAYE audit fields

Revision ID: 3d86fe677782
Revises: 3e6a34b801ab
Create Date: 2026-08-09 19:43:40.102474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d86fe677782'
down_revision = '3e6a34b801ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'regular_paye',
                sa.Numeric(precision=12, scale=2),
                server_default='0',
                nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                'irregular_paye',
                sa.Numeric(precision=12, scale=2),
                server_default='0',
                nullable=False
            )
        )

    op.execute(
        "UPDATE payroll_records "
        "SET regular_paye = paye, irregular_paye = 0"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('irregular_paye')
        batch_op.drop_column('regular_paye')

    # ### end Alembic commands ###
