"""classify recurring payroll items

Revision ID: 3e6a34b801ab
Revises: 1f8034f62773
Create Date: 2026-08-09 19:19:07.863653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6a34b801ab'
down_revision = '1f8034f62773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earning_classification', sa.String(length=30), server_default='Regular Allowance', nullable=False))
        batch_op.create_index(batch_op.f('ix_allowance_types_earning_classification'), ['earning_classification'], unique=False)

    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earning_classification', sa.String(length=30), server_default='Regular Allowance', nullable=False))
        batch_op.add_column(sa.Column('is_taxable', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('deduction_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tax_deductible', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tax_deductible', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('reduces_net_pay', sa.Boolean(), server_default=sa.text('true'), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_column('reduces_net_pay')
        batch_op.drop_column('is_tax_deductible')

    with op.batch_alter_table('deduction_types', schema=None) as batch_op:
        batch_op.drop_column('is_tax_deductible')

    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.drop_column('is_taxable')
        batch_op.drop_column('earning_classification')

    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowance_types_earning_classification'))
        batch_op.drop_column('earning_classification')

    # ### end Alembic commands ###
