"""add statutory rule sets and tax bands

Revision ID: 6a35fb3cdfb6
Revises: 005e4d2bb019
Create Date: 2026-07-20 21:10:55.351302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a35fb3cdfb6'
down_revision = '005e4d2bb019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_rule_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('nssa_employee_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('nssa_employer_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('nssa_monthly_ceiling', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aids_levy_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('paye_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('aids_levy_rate >= 0 AND aids_levy_rate <= 1', name='ck_rule_set_aids_levy_rate'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_rule_set_effective_date_range'),
    sa.CheckConstraint('nssa_employee_rate >= 0 AND nssa_employee_rate <= 1', name='ck_rule_set_nssa_employee_rate'),
    sa.CheckConstraint('nssa_employer_rate >= 0 AND nssa_employer_rate <= 1', name='ck_rule_set_nssa_employer_rate'),
    sa.CheckConstraint('nssa_monthly_ceiling >= 0', name='ck_rule_set_nssa_ceiling_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'currency', 'effective_from', name='uq_rule_set_name_currency_effective_from')
    )
    with op.batch_alter_table('statutory_rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_rule_sets_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_sets_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_sets_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_sets_is_active'), ['is_active'], unique=False)

    op.create_table('tax_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('band_order', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('upper_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.CheckConstraint('band_order > 0', name='ck_tax_band_order_positive'),
    sa.CheckConstraint('lower_limit >= 0', name='ck_tax_band_lower_limit_non_negative'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_tax_band_rate'),
    sa.CheckConstraint('upper_limit IS NULL OR upper_limit > lower_limit', name='ck_tax_band_valid_range'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['statutory_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_set_id', 'band_order', name='uq_tax_band_rule_set_order')
    )
    with op.batch_alter_table('tax_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_bands_rule_set_id'), ['rule_set_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_bands_rule_set_id'))

    op.drop_table('tax_bands')
    with op.batch_alter_table('statutory_rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_rule_sets_is_active'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_sets_effective_to'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_sets_effective_from'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_sets_currency'))

    op.drop_table('statutory_rule_sets')
    # ### end Alembic commands ###
