"""add recurring allowance and deduction configuration

Revision ID: 70d578ad0be4
Revises: c7b4bdb52ad3
Create Date: 2026-07-31 13:57:04.122533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d578ad0be4'
down_revision = 'c7b4bdb52ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowance_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calculation_method', sa.String(length=30), server_default='Fixed Amount', nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('default_percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('is_taxable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('default_amount >= 0', name='ck_allowance_type_default_amount_non_negative'),
    sa.CheckConstraint('default_percentage >= 0', name='ck_allowance_type_default_percentage_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowance_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_allowance_types_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowance_types_name'), ['name'], unique=True)

    op.create_table('deduction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), server_default='Voluntary', nullable=False),
    sa.Column('calculation_method', sa.String(length=30), server_default='Fixed Amount', nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('default_percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('employer_percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('is_statutory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reduces_net_pay', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('default_amount >= 0', name='ck_deduction_type_default_amount_non_negative'),
    sa.CheckConstraint('default_percentage >= 0', name='ck_deduction_type_default_percentage_non_negative'),
    sa.CheckConstraint('employer_percentage >= 0', name='ck_deduction_type_employer_percentage_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deduction_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deduction_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_deduction_types_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_deduction_types_name'), ['name'], unique=True)

    op.create_table('employee_allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allowance_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_employee_allowance_amount_non_negative'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_employee_allowance_valid_date_range'),
    sa.CheckConstraint('percentage >= 0', name='ck_employee_allowance_percentage_non_negative'),
    sa.ForeignKeyConstraint(['allowance_type_id'], ['allowance_types.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'allowance_type_id', name='uq_employee_allowance_employee_type')
    )
    with op.batch_alter_table('employee_allowances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_allowances_allowance_type_id'), ['allowance_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_allowances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_allowances_is_active'), ['is_active'], unique=False)

    op.create_table('employee_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('employer_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('employer_percentage', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_employee_deduction_amount_non_negative'),
    sa.CheckConstraint('employer_amount >= 0', name='ck_employee_deduction_employer_amount_non_negative'),
    sa.CheckConstraint('employer_percentage >= 0', name='ck_employee_deduction_employer_percentage_non_negative'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_employee_deduction_valid_date_range'),
    sa.CheckConstraint('percentage >= 0', name='ck_employee_deduction_percentage_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deduction_type_id'], ['deduction_types.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'deduction_type_id', name='uq_employee_deduction_employee_type')
    )
    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_deductions_deduction_type_id'), ['deduction_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_deductions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_deductions_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_is_active'))

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_deductions_is_active'))
        batch_op.drop_index(batch_op.f('ix_employee_deductions_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_deductions_deduction_type_id'))

    op.drop_table('employee_deductions')
    with op.batch_alter_table('employee_allowances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_allowances_is_active'))
        batch_op.drop_index(batch_op.f('ix_employee_allowances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_allowances_allowance_type_id'))

    op.drop_table('employee_allowances')
    with op.batch_alter_table('deduction_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deduction_types_name'))
        batch_op.drop_index(batch_op.f('ix_deduction_types_is_active'))
        batch_op.drop_index(batch_op.f('ix_deduction_types_code'))

    op.drop_table('deduction_types')
    with op.batch_alter_table('allowance_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowance_types_name'))
        batch_op.drop_index(batch_op.f('ix_allowance_types_is_active'))
        batch_op.drop_index(batch_op.f('ix_allowance_types_code'))

    op.drop_table('allowance_types')
    # ### end Alembic commands ###
