"""add employee payment method

Revision ID: aa26b9a5f43a
Revises: 0fa3b126bba8
Create Date: 2026-07-25 20:40:32.528727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa26b9a5f43a'
down_revision = '0fa3b126bba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=30), server_default='Cash', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
