"""add statutory rule set version history

Revision ID: ad9e3cbc2ffb
Revises: 60122994126a
Create Date: 2026-08-03 11:45:38.676608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9e3cbc2ffb'
down_revision = '60122994126a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_rule_set_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('source_preset_id', sa.Integer(), nullable=True),
    sa.Column('source_preset_key', sa.String(length=120), nullable=True),
    sa.Column('source_preset_version', sa.String(length=50), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['statutory_rule_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_preset_id'], ['statutory_presets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statutory_rule_set_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_id'), ['source_preset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_key'), ['source_preset_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_version'), ['source_preset_version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_rule_set_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_version'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_key'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_source_preset_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_rule_set_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_rule_set_versions_created_at'))

    op.drop_table('statutory_rule_set_versions')
    # ### end Alembic commands ###
