"""add payroll locking metadata

Revision ID: b1949dc7184d
Revises: aa26b9a5f43a
Create Date: 2026-07-26 19:36:07.221995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1949dc7184d'
down_revision = 'aa26b9a5f43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['locked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_periods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('locked_by')

    # ### end Alembic commands ###
