"""Create deductions table

Revision ID: b3ecf059bb1b
Revises: c117b8f5afb2
Create Date: 2026-07-12 21:56:32.704404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ecf059bb1b'
down_revision = 'c117b8f5afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_deduction_amount_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deductions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deductions_payroll_record_id'), ['payroll_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deductions_payroll_record_id'))
        batch_op.drop_index(batch_op.f('ix_deductions_employee_id'))

    op.drop_table('deductions')
    # ### end Alembic commands ###
