"""Create allowances table

Revision ID: c117b8f5afb2
Revises: 2fcf6b56b26b
Create Date: 2026-07-12 21:48:39.343533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c117b8f5afb2'
down_revision = '2fcf6b56b26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allowance_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_allowance_amount_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowances_payroll_record_id'), ['payroll_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowances_payroll_record_id'))
        batch_op.drop_index(batch_op.f('ix_allowances_employee_id'))

    op.drop_table('allowances')
    # ### end Alembic commands ###
