"""add database backed statutory preset library

Revision ID: c7046d0fd66c
Revises: 70d578ad0be4
Create Date: 2026-08-01 20:28:04.291855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7046d0fd66c'
down_revision = '70d578ad0be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_key', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('paye_enabled', sa.Boolean(), nullable=False),
    sa.Column('employee_contribution_name', sa.String(length=100), nullable=True),
    sa.Column('employee_contribution_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('employer_contribution_name', sa.String(length=100), nullable=True),
    sa.Column('employer_contribution_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('contribution_ceiling', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('levy_name', sa.String(length=100), nullable=True),
    sa.Column('levy_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('contribution_ceiling >= 0', name='ck_statutory_preset_ceiling'),
    sa.CheckConstraint('effective_to >= effective_from', name='ck_statutory_preset_effective_dates'),
    sa.CheckConstraint('employee_contribution_rate >= 0 AND employee_contribution_rate <= 1', name='ck_statutory_preset_employee_rate'),
    sa.CheckConstraint('employer_contribution_rate >= 0 AND employer_contribution_rate <= 1', name='ck_statutory_preset_employer_rate'),
    sa.CheckConstraint('levy_rate >= 0 AND levy_rate <= 1', name='ck_statutory_preset_levy_rate'),
    sa.CheckConstraint('tax_year >= 1900', name='ck_statutory_preset_tax_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'currency', 'tax_year', 'effective_from', name='uq_statutory_preset_country_currency_year')
    )
    with op.batch_alter_table('statutory_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_presets_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_country_name'), ['country_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_preset_key'), ['preset_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_statutory_presets_tax_year'), ['tax_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_presets_verification_status'), ['verification_status'], unique=False)

    op.create_table('statutory_preset_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('band_order', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('upper_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.CheckConstraint('band_order > 0', name='ck_statutory_preset_band_order'),
    sa.CheckConstraint('lower_limit >= 0', name='ck_statutory_preset_band_lower'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_statutory_preset_band_rate'),
    sa.CheckConstraint('upper_limit IS NULL OR upper_limit > lower_limit', name='ck_statutory_preset_band_range'),
    sa.ForeignKeyConstraint(['preset_id'], ['statutory_presets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_id', 'band_order', name='uq_statutory_preset_band_order')
    )
    with op.batch_alter_table('statutory_preset_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_preset_bands_preset_id'), ['preset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_preset_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_preset_bands_preset_id'))

    op.drop_table('statutory_preset_bands')
    with op.batch_alter_table('statutory_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_presets_verification_status'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_tax_year'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_preset_key'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_is_published'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_effective_to'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_effective_from'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_currency'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_country_name'))
        batch_op.drop_index(batch_op.f('ix_statutory_presets_country_code'))

    op.drop_table('statutory_presets')
    # ### end Alembic commands ###
