"""add email delivery history

Revision ID: c7b4bdb52ad3
Revises: a89bc1bf7fa9
Create Date: 2026-07-29 20:47:11.391759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b4bdb52ad3'
down_revision = 'a89bc1bf7fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_payroll_period_id'), ['payroll_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_payslip_id'), ['payslip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_sent_by_id'), ['sent_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_sent_by_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_sent_at'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_payslip_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_payroll_period_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_employee_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_created_at'))

    op.drop_table('email_deliveries')
    # ### end Alembic commands ###
