"""Built-in Zimbabwe statutory presets."""

from datetime import date, datetime
from decimal import Decimal

from app.models import StatutoryPreset


ZIMBABWE_PRESETS = [
    {
        "preset_key": "ZW_USD_2025_MONTHLY",
        "country_code": "ZW",
        "country_name": "Zimbabwe",
        "country_flag": "🇿🇼",
        "currency": "USD",
        "tax_year": 2025,
        "tax_period_label": "2025",
        "version": "1.0",
        "name": "Zimbabwe USD Statutory Rules 2025",
        "engine_type": StatutoryPreset.ENGINE_ZIMBABWE,
        "effective_from": date(2025, 1, 1),
        "effective_to": date(2025, 12, 31),
        "verification_status": "Verified",
        "source_name": "ZIMRA USD PAYE Tax Tables January–December 2025",
        "source_description": (
            "Official Zimbabwe monthly foreign-currency PAYE table."
        ),
        "source_reference": "ZIMRA USD PAYE Tax Tables 2025",
        "official_source_url": None,
        "last_verified_at": datetime(2026, 8, 2),
        "notes": "Fully supported by the current Zimbabwe payroll engine.",
        "paye_enabled": True,
        "employee_contribution_name": "NSSA Employee",
        "employee_contribution_rate": Decimal("0.045000"),
        "employer_contribution_name": "NSSA Employer",
        "employer_contribution_rate": Decimal("0.045000"),
        "contribution_ceiling": Decimal("700.00"),
        "levy_name": "AIDS Levy",
        "levy_rate": Decimal("0.030000"),
        "supports_import": True,
        "supports_payroll": True,
        "is_published": True,
        "is_locked": True,
        "bands": [
            {"band_order": 1, "lower_limit": Decimal("0.00"), "upper_limit": Decimal("100.00"), "rate": Decimal("0.000000")},
            {"band_order": 2, "lower_limit": Decimal("100.00"), "upper_limit": Decimal("300.00"), "rate": Decimal("0.200000")},
            {"band_order": 3, "lower_limit": Decimal("300.00"), "upper_limit": Decimal("1000.00"), "rate": Decimal("0.250000")},
            {"band_order": 4, "lower_limit": Decimal("1000.00"), "upper_limit": Decimal("2000.00"), "rate": Decimal("0.300000")},
            {"band_order": 5, "lower_limit": Decimal("2000.00"), "upper_limit": Decimal("3000.00"), "rate": Decimal("0.350000")},
            {"band_order": 6, "lower_limit": Decimal("3000.00"), "upper_limit": None, "rate": Decimal("0.400000")},
        ],
    },
    {
        "preset_key": "ZW_USD_2026_CATALOGUE",
        "country_code": "ZW",
        "country_name": "Zimbabwe",
        "country_flag": "🇿🇼",
        "currency": "USD",
        "tax_year": 2026,
        "tax_period_label": "2026",
        "version": "catalogue-1.0",
        "name": "Zimbabwe USD Statutory Rules 2026",
        "engine_type": StatutoryPreset.ENGINE_ZIMBABWE,
        "effective_from": date(2026, 1, 1),
        "effective_to": date(2026, 12, 31),
        "verification_status": "Source Located",
        "source_name": "ZIMRA 2026 Individual PAYE Tax Tables",
        "source_description": (
            "Catalogue entry created from ZIMRA's 2026 PAYE listing. "
            "Exact bands must be verified from the correct official table "
            "before import is enabled."
        ),
        "source_reference": "ZIMRA Tax Tables 2026",
        "official_source_url": None,
        "last_verified_at": datetime(2026, 8, 2),
        "notes": "Visible in the library; import remains blocked pending band verification.",
        "paye_enabled": False,
        "employee_contribution_name": "NSSA Employee",
        "employee_contribution_rate": Decimal("0.000000"),
        "employer_contribution_name": "NSSA Employer",
        "employer_contribution_rate": Decimal("0.000000"),
        "contribution_ceiling": Decimal("0.00"),
        "levy_name": "AIDS Levy",
        "levy_rate": Decimal("0.000000"),
        "supports_import": False,
        "supports_payroll": True,
        "is_published": True,
        "is_locked": True,
        "bands": [],
    },
    {
        "preset_key": "ZW_ZWG_2026_CATALOGUE",
        "country_code": "ZW",
        "country_name": "Zimbabwe",
        "country_flag": "🇿🇼",
        "currency": "ZWG",
        "tax_year": 2026,
        "tax_period_label": "2026",
        "version": "catalogue-1.0",
        "name": "Zimbabwe ZWG Statutory Rules 2026",
        "engine_type": StatutoryPreset.ENGINE_ZIMBABWE,
        "effective_from": date(2026, 1, 1),
        "effective_to": date(2026, 12, 31),
        "verification_status": "Source Located",
        "source_name": "ZIMRA 2026 Individual PAYE Tax Tables",
        "source_description": (
            "Catalogue entry for the 2026 local-currency PAYE table. "
            "Exact bands must be verified before import is enabled."
        ),
        "source_reference": "ZIMRA Tax Tables 2026",
        "official_source_url": None,
        "last_verified_at": datetime(2026, 8, 2),
        "notes": "Visible in the library; import remains blocked pending band verification.",
        "paye_enabled": False,
        "employee_contribution_name": "NSSA Employee",
        "employee_contribution_rate": Decimal("0.000000"),
        "employer_contribution_name": "NSSA Employer",
        "employer_contribution_rate": Decimal("0.000000"),
        "contribution_ceiling": Decimal("0.00"),
        "levy_name": "AIDS Levy",
        "levy_rate": Decimal("0.000000"),
        "supports_import": False,
        "supports_payroll": True,
        "is_published": True,
        "is_locked": True,
        "bands": [],
    },
]
